import CaloriesResult from "./CaloriesResult";
import ChooseSearch from "./ChooseSearch";
import CameraScreen from "./CameraScreen";
import LoginScreen from "./LoginScreen";
import NutResult from "./NutResult";
import Search from "./Search";
import SearchDetail from "./SearchDetail";
import SetGoal from "./SetGoal";
import StaticPie from "./StaticPie";
import MyPage from "./MyPage";
import Temp from "./Temp";
import Home from "./Home";
import RegisterFoodName from "./RegisterFoodName";
import RegisterFoodQuantity from "./RegisterFoodQuantity";
import RegisterFoodNutrition from "./RegisterFoodNutrition";
export { CaloriesResult, ChooseSearch, CameraScreen, LoginScreen, NutResult, Search, SearchDetail, SetGoal, StaticPie, MyPage, Temp, Home, RegisterFoodName, RegisterFoodQuantity, RegisterFoodNutrition };