import CaloriesResult from "./CaloriesResult";
import ChooseSearch from "./ChooseSearch";
import CameraScreen from "./CameraScreen";
import LoginScreen from "./LoginScreen";
import NutResult from "./NutResult";
import Search from "./Search";
import SearchDetail from "./SearchDetail";
import SetGoal from "./SetGoal";
import StaticPie from "./StaticPie";
import MyPage from "./MyPage";
import Temp from "./Temp";
import Home from "./Home";
import StatisticsRecord from "./StatisticsRecord";
import RegisterFoodName from "./RegisterFoodName";
import RegisterFoodQuantity from "./RegisterFoodQuantity";
import RegisterFoodNutrition from "./RegisterFoodNutrition";
import MealDetail from "./MealDetail";
import Shop from "./Shop"
export { CaloriesResult, ChooseSearch, CameraScreen, LoginScreen, NutResult, Search, SearchDetail, SetGoal, StaticPie, MyPage, Temp, Home, RegisterFoodName, RegisterFoodQuantity, RegisterFoodNutrition, StatisticsRecord, MealDetail, Shop};